### ISSUE TITLE
The method of generating a .FMU for Windows platform？

### ISSUE THREAD

**Issue by Asukaleo-aa** [DLR-RY/FMU4FOAM#13]
Thanks for developing this framework，it's really a good job!
i see there are some fmu files for Windows generated by FMU4FORM in the documentation, but i don't know how to realize it, could you please give some more detailed tutorials？
Thanks a million.

**Comment by HenningScheufler** [comment]
The easiest way to use this library on windows (currently is to run it in the WSL)
