### ISSUE TITLE
Need for a few updates

### ISSUE THREAD

**Issue by carlo-fiorina** [DLR-RY/FMU4FOAM#16]
Hi,
I have recently installed FMU4FOAM on a new machine with the latest version of OpenFOAM (2212).
I have run into a few issues:
- The conan scripting is not compatible with conan 2.x. For the installation to work, one has to force  `pip install conan==1.58.0`
- There are a couple of functionalities that do not compile anymore on the latest OpenFOAM (coupledWallHeatFluxTemperatureFvPatchScalarField and extForces). I am hoping I will be able at some point to fix that and submit a merge request myself...

In addition, I think it would be useful to add in the documentation that a user will need to
`pip install  OMSimulator `
to be able to run a test.

Many thanks,

Carlo

**Comment by HenningScheufler** [comment]
i updated the documentation accordingly

Looking forward to a pull request with conan 2.0

**Comment by carlo-fiorina** [comment]
Thanks!
I'try to  look into coupledWallHeatFluxTemperatureFvPatchScalarField and extForces.
Unfortunately, I am too unfamiliar with conan to help out there in the short term

**Comment by carlo-fiorina** [comment]
Hi again,
I am having some troubles authenticating on github. However, the changes to do  to obtain compatibility with the most recent OpenFOAM (2212) are minimal and associated with the following 3 files:
- FMU4FOAM/ECI4FOAM/src/externalComm/Make/options
FMU4FOAM/ECI4FOAM/src/externalComm/externalIO/input/BC/coupledWallHeatFluxTemperature/coupledWallHeatFluxTemperature.C
- FMU4FOAM/ECI4FOAM/src/externalComm/externalIO/output/extForces/extForces.C

I am attaching the 3 modified files.
[ECImod.zip](https://github.com/DLR-RY/FMU4FOAM/files/11055045/ECImod.zip)

**Comment by carlo-fiorina** [comment]
Hi again, I have created a pull request to the ECI4FOAM repository with the modifications mentioned in the previous post. This should allow compilation on OpenFOAM 2212

**Comment by HenningScheufler** [comment]
sucessfully merged. Thanks for the pull request!
